/**
 * Structured glossary data, transcribed from trading-mastery/glossary/README.md.
 * Powers the inline <Term> tooltip and the standalone /learn/glossary page.
 * Each entry mirrors the source's Simple -> Technical -> Example structure.
 */

export interface GlossaryEntry {
  id: string;
  term: string;
  simple: string;
  technical: string;
  example?: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { id: "arbitrage", term: "Arbitrage", simple: "Profiting from the same thing being priced differently in two places, with little/no risk.", technical: "Simultaneously buying and selling related instruments to capture a price discrepancy; the force that keeps related prices consistent.", example: "If NIFTY futures trade far above the NIFTY spot basket, arbitrageurs sell futures and buy the basket until the gap closes." },
  { id: "ask-offer", term: "Ask (Offer)", simple: "The lowest price a seller will accept right now.", technical: "The best (lowest) resting sell limit order in the order book.", example: "Best ask ₹500.20 means you can buy immediately at ₹500.20." },
  { id: "atr-average-true-range", term: "ATR (Average True Range)", simple: "How much a price typically moves in a period.", technical: "Average of the True Range (max of high−low, |high−prev close|, |low−prev close|) over n periods; a volatility measure in price units.", example: "Daily ATR ₹25 → set a stop 2×ATR = ₹50 away." },
  { id: "backtest", term: "Backtest", simple: "Testing a strategy on past data.", technical: "Simulating a rule set over historical prices to estimate performance, ideally with costs, slippage, and out-of-sample validation.", example: "Running a 20/50 SMA crossover over 10 years of NIFTY data." },
  { id: "basis", term: "Basis", simple: "The gap between a futures price and the spot price.", technical: "Basis = Futures − Spot; converges to zero at expiry.", example: "NIFTY spot 24,000, near-month future 24,080 → basis +80." },
  { id: "bid", term: "Bid", simple: "The highest price a buyer will pay right now.", technical: "The best (highest) resting buy limit order in the order book.", example: "Best bid ₹499.80 means you can sell immediately at ₹499.80." },
  { id: "bollinger-bands", term: "Bollinger Bands", simple: "A moving average with volatility bands above and below.", technical: "Middle SMA with upper/lower bands at ±k standard deviations (often 20-period, k=2); widen with volatility.", example: "A \"squeeze\" (narrow bands) may precede a breakout." },
  { id: "cagr-compound-annual-growth-rate", term: "CAGR (Compound Annual Growth Rate)", simple: "The steady yearly rate that would produce your actual multi-year growth.", technical: "(P_end/P_start)^(1/n) − 1; the geometric growth rate.", example: "₹1L → ₹2L over 6 years → CAGR ≈ 12.2%." },
  { id: "calmar-ratio", term: "Calmar Ratio", simple: "Return divided by worst drawdown.", technical: "Annualized return ÷ |max drawdown|; rewards smooth growth.", example: "12% return with −10% MDD → Calmar 1.2." },
  { id: "clearing-corporation", term: "Clearing Corporation", simple: "The middleman that guarantees your trade completes.", technical: "Central counterparty (CCP) that steps between buyer and seller, nets obligations, and removes counterparty risk.", example: "NSE Clearing (NCL) / ICCL in India." },
  { id: "compounding", term: "Compounding", simple: "Earning returns on your past returns.", technical: "Exponential growth FV = PV(1+r)^n; also compounds costs and losses against you.", example: "₹1L at 12% for 30y ≈ ₹30L." },
  { id: "contango-and-backwardation", term: "Contango and Backwardation", simple: "Whether futures are priced above (contango) or below (backwardation) spot.", technical: "Contango = futures > spot (typical for cost-of-carry); backwardation = futures < spot.", example: "Commodity futures in contango roll at a cost over time." },
  { id: "correlation", term: "Correlation", simple: "How much two things move together (−1 to +1).", technical: "Standardized covariance; +1 perfectly together, −1 perfectly opposite, 0 no linear relationship.", example: "Two large private banks are highly positively correlated." },
  { id: "delta", term: "Delta", simple: "How much an option's price moves per ₹1 in the underlying.", technical: "∂(option price)/∂(underlying); 0→1 for calls, 0→−1 for puts; roughly approximates probability of finishing ITM.", example: "A 0.4-delta call gains ~₹0.40 per ₹1 rise." },
  { id: "demat-account", term: "Demat Account", simple: "Where your shares are held electronically.", technical: "Dematerialized securities account at a depository (NSDL/CDSL), serviced by a DP.", example: "Buying INFY credits shares to your demat on settlement." },
  { id: "depository", term: "Depository", simple: "The institution that stores shares as ledger entries.", technical: "Holds securities electronically and records ownership; India has NSDL and CDSL." },
  { id: "diversification", term: "Diversification", simple: "Not putting all your eggs in one basket.", technical: "Combining uncorrelated assets to reduce portfolio risk without proportionally reducing expected return.", example: "Spreading across sectors and asset classes, not ten bank stocks." },
  { id: "dp-charges", term: "DP Charges", simple: "A flat fee when you sell delivery shares.", technical: "Depository Participant charge on demat debits, ~₹13–20 + GST per ISIN per day (delivery sell); not on intraday/F&O. 🗓️" },
  { id: "drawdown-maximum-drawdown", term: "Drawdown (Maximum Drawdown)", simple: "How far you've fallen from your peak.", technical: "Peak-to-trough decline in equity; max drawdown is the largest such fall. Recovery is asymmetric (−50% needs +100%).", example: "Equity ₹1.2L → ₹0.9L is a −25% drawdown." },
  { id: "emh-efficient-market-hypothesis", term: "EMH (Efficient Market Hypothesis)", simple: "Prices already reflect known information, so beating the market is hard.", technical: "The claim that asset prices incorporate available information; strong/semi-strong/weak forms.", example: "Most active funds underperform index funds after fees." },
  { id: "elm-extreme-loss-margin", term: "ELM (Extreme Loss Margin)", simple: "Extra margin buffer for bad-case moves.", technical: "A margin component covering losses beyond standard (VaR/SPAN) margins; raised near F&O expiry under SEBI rules. 🗓️" },
  { id: "expectancy", term: "Expectancy", simple: "Average profit per trade.", technical: "E = W·A_w − L·A_l (or in R units); the number that decides if a strategy makes money.", example: "45% win, +₹8k avg win, −₹4k avg loss → E = ₹1,400/trade (before costs)." },
  { id: "free-float", term: "Free Float", simple: "Shares actually available to trade publicly.", technical: "Shares outstanding minus locked-in/promoter/strategic holdings; used to weight indices.", example: "A company may be large by market cap but have low free float." },
  { id: "futures", term: "Futures", simple: "A contract to buy/sell something at a set price on a future date.", technical: "Standardized, exchange-traded, margined, marked-to-market forward contract.", example: "One NIFTY future controls a large notional with a fraction posted as margin." },
  { id: "gamma", term: "Gamma", simple: "How fast an option's delta changes.", technical: "∂delta/∂(underlying); highest ATM near expiry; short options have negative gamma (losses accelerate).", example: "A short straddle's delta swings violently against you on a big move." },
  { id: "gap", term: "Gap", simple: "When price opens far from the previous close.", technical: "A discontinuity (no trades between) often from overnight news; makes stops slip.", example: "A stock closes ₹500, opens ₹460 after bad results." },
  { id: "greeks", term: "Greeks", simple: "Numbers describing how an option reacts to price, time, volatility, and rates.", technical: "Delta, gamma, theta, vega, rho — partial derivatives of option value." },
  { id: "hedging", term: "Hedging", simple: "Taking a position to reduce risk in another.", technical: "Offsetting exposure via a negatively-correlated instrument (e.g. a protective put).", example: "An investor buys index puts to protect a stock portfolio." },
  { id: "hft-high-frequency-trading", term: "HFT (High-Frequency Trading)", simple: "Ultra-fast automated trading.", technical: "Latency-sensitive strategies (market making, arbitrage) executing in microseconds.", example: "Firms co-locate servers next to the exchange." },
  { id: "implied-volatility-iv", term: "Implied Volatility (IV)", simple: "The volatility \"baked into\" an option's price.", technical: "The volatility input that makes a pricing model match the market premium; forward-looking, an opinion.", example: "IV spikes before earnings, then collapses (\"vol crush\")." },
  { id: "index", term: "Index", simple: "A basket of stocks summarised by one number.", technical: "A rules-based, usually free-float market-cap-weighted portfolio.", example: "NIFTY 50, SENSEX, BANKNIFTY." },
  { id: "intrinsic-value-options", term: "Intrinsic Value (Options)", simple: "What an option is worth if exercised now.", technical: "Call: max(Spot−Strike,0); Put: max(Strike−Spot,0); never negative.", example: "24000 call with spot 24,150 → intrinsic 150." },
  { id: "kelly-criterion", term: "Kelly Criterion", simple: "The bet size that maximizes long-run growth.", technical: "f* = (bp−q)/b; forbids betting a negative-edge game; usually applied fractionally (¼–½).", example: "p=0.55, b=1 → f*=10%, but bet ~5% (half-Kelly)." },
  { id: "leverage", term: "Leverage", simple: "Using borrowed money/margin to trade bigger.", technical: "Controlling a position larger than your capital; multiplies gains and losses; introduces margin calls.", example: "5× leverage turns a 10% move into a 50% P&L swing." },
  { id: "limit-order", term: "Limit Order", simple: "Buy/sell only at your price or better.", technical: "An order that rests in the book until matched at the specified price or better; guarantees price, not execution.", example: "\"Buy 100 @ ₹499\" waits for a seller at ₹499." },
  { id: "liquidity", term: "Liquidity", simple: "How easily you can trade without moving the price.", technical: "Depth and tightness of the market; ability to transact size near fair value quickly.", example: "RELIANCE is liquid; a thin smallcap is not." },
  { id: "log-return", term: "Log Return", simple: "A return measured with logarithms; adds up over time.", technical: "ln(P_t/P_t-1); time-additive and better-behaved than simple returns.", example: "₹100→₹110 log return ≈ 9.53%." },
  { id: "margin", term: "Margin", simple: "Collateral you post to hold a leveraged position.", technical: "Funds required by the broker/exchange (e.g. SPAN + exposure + ELM); a margin call demands more or force-liquidates.", example: "₹1L margin controls a ₹5L position." },
  { id: "market-capitalization", term: "Market Capitalization", simple: "The total value of a company's shares.", technical: "Share price × total shares outstanding.", example: "₹1,400 × 6.7B shares ≈ ₹9.4L crore." },
  { id: "market-depth", term: "Market Depth", simple: "How much size is available at each price.", technical: "The quantities resting at each level of the order book; determines price impact of orders.", example: "Only 400 shares at the best ask → a 2,000 order walks the book." },
  { id: "market-maker", term: "Market Maker", simple: "A trader who always quotes both a buy and sell price.", technical: "A liquidity provider earning the spread for continuously posting bids and asks; withdraws in stress." },
  { id: "market-order", term: "Market Order", simple: "Buy/sell immediately at the best available price.", technical: "An order that crosses the spread and consumes resting liquidity; guarantees execution, not price.", example: "\"Buy 100 at market\" fills at the best ask(s)." },
  { id: "moneyness", term: "Moneyness", simple: "Whether an option has intrinsic value.", technical: "ITM (in the money), ATM (at the money), OTM (out of the money) relative to strike vs spot.", example: "With spot 24,150, a 24,000 call is ITM." },
  { id: "monte-carlo-simulation", term: "Monte Carlo Simulation", simple: "Running many \"what if\" random scenarios.", technical: "Repeatedly resampling/shuffling to estimate the distribution of outcomes (e.g. drawdowns).", example: "Shuffle trade order 5,000× to see worst-case equity paths." },
  { id: "mwpl-market-wide-position-limit", term: "MWPL (Market-Wide Position Limit)", simple: "A cap on total F&O positions in a stock.", technical: "When aggregate open interest crosses ~95% of MWPL, the stock enters an F&O ban (no fresh positions). 🗓️" },
  { id: "nav-net-asset-value", term: "NAV (Net Asset Value)", simple: "The per-unit value of a fund's holdings.", technical: "(Assets − liabilities) / units; ETFs trade near NAV via creation/redemption.", example: "A mutual fund unit is bought/sold at NAV." },
  { id: "open-interest-oi", term: "Open Interest (OI)", simple: "How many derivative contracts are currently open.", technical: "Total outstanding (unclosed) contracts; differs from volume (trades).", example: "Rising OI + rising price is often read as fresh longs (with caveats)." },
  { id: "order-book", term: "Order Book", simple: "The live list of all buy and sell orders.", technical: "The limit order book: bids and asks sorted by price and time.", example: "Best bid ₹499.80 / best ask ₹500.20." },
  { id: "overfitting", term: "Overfitting", simple: "A model that memorizes the past and predicts nothing.", technical: "Fitting noise rather than signal; too many parameters/trials relative to data.", example: "Tweaking rules until the backtest is perfect, then failing live." },
  { id: "pcr-put-call-ratio", term: "PCR (Put-Call Ratio)", simple: "Puts vs calls outstanding/traded.", technical: "Put OI (or volume) ÷ call OI; sometimes read as a contrarian sentiment gauge (weak, regime-dependent).", example: "High PCR = heavy put positioning." },
  { id: "pe-ratio", term: "P/E Ratio", simple: "Price paid per rupee of earnings.", technical: "Price ÷ EPS; a valuation multiple that misleads for cyclicals, loss-makers, and differing growth/quality.", example: "₹1,000 price, ₹50 EPS → P/E 20." },
  { id: "position-sizing", term: "Position Sizing", simple: "How many shares/lots to trade.", technical: "Quantity chosen so a stop-out loses a fixed fraction of capital: Account × Risk% ÷ (Entry − Stop).", example: "₹5L × 1% ÷ ₹30 = 166 shares." },
  { id: "price-discovery", term: "Price Discovery", simple: "How the market figures out a price.", technical: "The process by which buying/selling converges on a price reflecting available information." },
  { id: "primary-vs-secondary-market", term: "Primary vs. Secondary Market", simple: "Where securities are created vs. where they trade.", technical: "Primary: issuer sells new securities (IPO), gets the money; secondary: investors trade existing securities among themselves.", example: "IPO (primary) vs buying INFY on NSE (secondary)." },
  { id: "ipo", term: "IPO", simple: "A company's first public share sale.", technical: "Initial Public Offering; a primary-market issuance via prospectus and price band, funds blocked via ASBA/UPI." },
  { id: "r-multiple", term: "R Multiple", simple: "Profit/loss measured in units of your risk.", technical: "1R = amount risked (entry−stop); outcomes expressed as multiples (+2R, −1R).", example: "Risk ₹5k, make ₹10k → +2R." },
  { id: "return", term: "Return", simple: "Your gain/loss as a percentage.", technical: "(End − Start + Income)/Start; distinguish arithmetic vs geometric (CAGR).", example: "₹200→₹230 + ₹4 dividend on ₹200 = 17%." },
  { id: "risk-of-ruin", term: "Risk of Ruin", simple: "The chance a losing streak wipes you out.", technical: "Probability equity falls below a non-recoverable threshold; driven by edge, bet size, and bankroll.", example: "Risking 10%/trade makes ordinary streaks catastrophic." },
  { id: "risk-per-trade", term: "Risk Per Trade", simple: "How much you'll lose if a trade hits its stop.", technical: "A fixed fraction of capital (commonly 0.5–2%) risked per position.", example: "₹5L account, 1% → ₹5,000 risk." },
  { id: "rsi", term: "RSI", simple: "A 0–100 gauge of recent gains vs losses.", technical: "Relative Strength Index; >70 \"overbought,\" <30 \"oversold\"; a mean-reversion bet that fails in strong trends.", example: "RSI can stay >70 for weeks in an uptrend." },
  { id: "settlement", term: "Settlement", simple: "The actual transfer of shares and cash.", technical: "Post-trade pay-in/pay-out via clearing corp and depositories; India: T+1 default, optional T+0 for top-500. 🗓️", example: "Buy today, shares in demat on T+1." },
  { id: "sharpe-ratio", term: "Sharpe Ratio", simple: "Return per unit of risk (volatility).", technical: "(R_p − R_f)/σ_p, usually annualized; penalizes up and down volatility equally; gameable by tail-risk strategies.", example: "18% return, 12% vol, 6% Rf → 1.0." },
  { id: "short-selling", term: "Short Selling", simple: "Betting a price will fall by selling first.", technical: "Selling borrowed shares to buy back later; loss is theoretically unbounded; squeeze risk.", example: "Retail cash shorts in India are usually intraday-only; multi-day via F&O/SLBM." },
  { id: "slippage", term: "Slippage", simple: "Getting a worse price than expected.", technical: "Difference between expected and executed price from thin depth, fast moves, or gaps.", example: "Market buy fills at ₹500.24 vs the ₹500.20 you saw." },
  { id: "sortino-ratio", term: "Sortino Ratio", simple: "Sharpe, but only counting downside swings.", technical: "(R_p − R_f)/σ_downside; better for asymmetric strategies." },
  { id: "spread-bid-ask", term: "Spread (Bid-Ask)", simple: "The gap between the best buy and sell prices.", technical: "Ask − Bid; a real round-trip cost; wide in illiquid names.", example: "Bid 499.80 / Ask 500.20 → spread 0.40." },
  { id: "stop-loss", term: "Stop Loss", simple: "A pre-set exit that caps a loss.", technical: "Stop-market (guarantees exit, not price) or stop-limit (guarantees price, not fill); placed where the thesis is wrong.", example: "Long at ₹1,400, stop ₹1,370." },
  { id: "stt-securities-transaction-tax", term: "STT (Securities Transaction Tax)", simple: "A government tax on trades.", technical: "Charged on turnover/premium by segment; e.g. delivery 0.1% both sides, options 0.15% on premium (sell) — rates change (last revised 1 Apr 2026). 🗓️" },
  { id: "straddle-strangle", term: "Straddle / Strangle", simple: "Buying (or selling) both a call and a put to bet on volatility.", technical: "Straddle = same strike; strangle = OTM strikes; long = bet on a big move, short = bet on calm (undefined risk).", example: "Long ATM straddle profits on a large move either way." },
  { id: "t1-t0", term: "T+1 / T+0", simple: "How many days until a trade settles.", technical: "T+1 = one business day (India default since 2023); T+0 = same day (optional, top-500). 🗓️" },
  { id: "theta", term: "Theta", simple: "How much an option loses to time each day.", technical: "∂(option price)/∂time; negative for long options (decay), positive for sellers; accelerates near expiry.", example: "An ATM weekly bleeds value over a flat weekend." },
  { id: "time-value-extrinsic-value", term: "Time Value (Extrinsic Value)", simple: "The part of an option's price that isn't intrinsic.", technical: "Premium − intrinsic; the market's price for future possibility; decays to zero at expiry.", example: "OTM options are all time value." },
  { id: "tracking-error", term: "Tracking Error", simple: "How far an ETF/fund drifts from its index.", technical: "Std deviation of the fund's return minus the benchmark's.", example: "A NIFTY ETF slightly lagging NIFTY." },
  { id: "valuation", term: "Valuation", simple: "Estimating what a business is worth.", technical: "DCF (present value of future cash flows) and relative multiples (P/E, EV/EBITDA); assumption-sensitive." },
  { id: "vega", term: "Vega", simple: "How much an option's price moves per 1-point change in IV.", technical: "∂(option price)/∂(implied vol); positive for long options; source of \"right direction, still lost\" via vol crush." },
  { id: "volatility", term: "Volatility", simple: "How much prices swing around.", technical: "Std deviation of returns; historical (realized) vs implied; clusters over time.", example: "India VIX gauges expected NIFTY volatility." },
  { id: "vwap", term: "VWAP", simple: "The volume-weighted average price of the day.", technical: "Σ(price×volume)/Σ(volume), resets each session; an institutional execution benchmark." },
  { id: "walk-forward-analysis", term: "Walk-Forward Analysis", simple: "Repeatedly optimizing on the past and testing on the next slice.", technical: "Rolling train/test windows stitched into an out-of-sample curve; the gold standard of validation." },
  { id: "win-rate", term: "Win Rate", simple: "The fraction of trades that are winners.", technical: "Wins ÷ total trades; meaningless without average win/loss sizes.", example: "A 70% win rate can still lose money." },
];

export function getGlossaryEntry(id: string): GlossaryEntry | undefined {
  return GLOSSARY.find((g) => g.id === id);
}
